### ISSUE TITLE
3910. Дефис в имени

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#118]
Standard: 

> 0.25  PER [lastname : штайнмайер, firstname : франк, firstname : вальтер]

Test: 

> 0.25 PER [lastname : штайнмайер, firstname : франк-вальтер]

Франк-Вальтер, наверное, правильнее?

**Comment by vbocharov** [comment]
attn @StanDzh 

Компаратор ожидает, что в таких случаях будет два разных имени. Это описано в документе, который рассылал оргкомитет 29 января с темой "FactRuEval2016 - дорожка 2"
