### ISSUE TITLE
3894.Пробелы у тире

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#127]
Пробелы у тире – вроде как договаривались, что должно делаться сравнение без учета пробелов
Test:

> 0.00 ORG [name : петербург-пятый канал]

Standard:

> 0.00

 ORG [name : телерадиокомпания "петербург — пятый канал" | петербург — пятый канал телерадиокомпания | петербург — пятый канал | "петербург — пятый канал" телерадиокомпания | "петербург — пятый канал" | телерадиокомпания петербург — пятый канал]

**Comment by StanDzh** [comment]
Поправил импорт, добавил тест, залью в следующем коммите
