### ISSUE TITLE
список замеченных ошибок подряд

### ISSUE THREAD

**Issue by alexandr-j** [dialogue-evaluation/factRuEval-2016#128]

**Comment by alexandr-j** [comment]
Первая дорожка без LocOrg

book_3811
- Организации размечены как локации
  LOC <217; 228> "роскомнадзор"
  LOC <379; 391> "роскомнадзоре"
  LOC <477; 480> "раэк"
  LOC <1056; 1067> "роскомнадзор"
  LOC <1264; 1276> "роскомнадзора"
  LOC <3374; 3386> "роскомнадзоре"
  LOC <3641; 3652> "роскомнадзор"

book_3809
- Сущности не размечены в эталоне
  ORG <20; 30> "саммит нато"
  ORG <120; 131> "саммита нато"
  ORG <1333; 1343> "саммит нато"
  ORG <2113; 2124> "саммите нато"

book_3801
- США ошибочно помечена как организация
  ORG <3672; 3674> "сша"

book_3799
- Лишнее слово «британская» в сущности
  ORG <132; 154> "британская the guardian"

book_3797
- Роскосмос  ошибочно помечен как локация
  LOC <1545; 1554> "роскосмоса"

book_3796
- Не размеченные в эталоне сущности
  ORG <1647; 1655> "интернете"
  ORG <2012; 2023> "коллегии фсб"
  ORG <2358; 2366> "интернете"
  ORG <3162; 3170> "интернета"

book_3775
- Не размеченные в эталоне сущности
  ORG <323; 331> "интернете"

book_3774
- Организация помечена как локация
  LOC <1219; 1232> "европарламенте"

book_3770
- Неверные границы сущностей
  ------STANDARD------
  0.00 ORG <231; 233> "фнс"
  0.00 ORG <269; 271> "фтс"
  0.00 ORG <736; 738> "фас"
  0.00 ORG <774; 776> "фст"
  --------TEST--------
  0.75       ORG <201; 234> "федеральной налоговой службы (фнс)"       =             ORG <201; 228> "федеральной налоговой службы"
  0.75       ORG <238; 272> "федеральной таможенной службы (фтс)"   =             ORG <238; 266> "федеральной таможенной службы"
  0.75       ORG <700; 739> "федеральной антимонопольной службы (фас)"      =             ORG <700; 733> "федеральной антимонопольной службы"
  0.80      ORG <743; 777> "федеральной службы по тарифам (фст)"     =             ORG <743; 771> "федеральной службы по тарифам"

book_3765
- Не размеченные в эталоне сущности
  ORG <908; 918> "дизайн года"
  ORG <1260; 1278> "жюри "дизайна года""
  ORG <1411; 1441> "судейской команды "дизайн года""

book_3764
- Неверные границы сущности
  ------STANDARD------
  0.67       ORG <7; 25> ""большой восьмерки"" =             ORG <0; 25> "саммит "большой восьмерки""
  0.67       ORG <151; 169> ""большой восьмерки""          =             ORG <143; 169> "саммита "большой восьмерки""
  0.50       ORG <714; 715> "g8"     =             ORG <706; 715> "саммита g8"
  0.50       ORG <892; 893> "g8"     =             ORG <885; 893> "саммит g8"
- Организация помечена как локация
  LOC <719; 728> ""сколково""
  LOC <897; 906> ""сколково""

book_3758
- Ошибочная сущность в эталоне
  LOC <584; 608> "корея предложила северной"

book_3757
- Организация помечена как локация
  LOC <1586; 1587> "ес"
  LOC <2426; 2427> "ес"

book_3746
- Организации помечены как локации
  LOC <57; 58> "ес"
  LOC <217; 225> "евросоюза"
  LOC <317; 318> "ес"
  LOC <322; 325> "нато"
  LOC <567; 568> "ес"
  LOC <875; 883> "евросоюза"
  LOC <998; 999> "ес"
  LOC <1454; 1455> "ес"
  LOC <1572; 1579> "евросоюз"

book_3744
- Организации помечены как локации
  LOC <1208; 1216> "евросоюза"
  LOC <1581; 1582> "ес"
  LOC <1798; 1806> "евросоюзу"
  LOC <2283; 2290> "евросоюз"
  LOC <2395; 2396> "ес"

book_3734
- Неверные границы сущности
  ------STANDARD------
  0.80    ORG <546; 590> "международной организации гражданской авиации"         =             ORG <546; 597> "международной организации гражданской авиации (icao)"
- Локации помечены как организации
  ORG <1840; 1856> "донецкой областью"
  ORG <3434; 3440> "донецке"
- Не размеченные в эталоне сущности
  ORG <2398; 2408> "саммит g-20"
  ORG <4750; 4751> "ес"
  ORG <5221; 5228> "facebook"

book_3714
- Неверные границы сущности
  ------STANDARD------
  0.50    ORG <1386; 1387> "g7" =             ORG <1378; 1387> "саммита g7"
  0.50    ORG <2199; 2200> "g7" =             ORG <2190; 2200> "саммитом g7"
  0.50    ORG <2258; 2259> "g7" =             ORG <2250; 2259> "саммита g7"
- Организации помечены как локации
  LOC <2442; 2443> "ес"

book_3702
- Организации помечены как локации
  LOC <2007; 2008> "ес"
  LOC <2987; 2998> "еврокомиссии"
- Не размеченная в эталоне сущность
  ORG <1209; 1258> "подразделения вооруженных сил российской федерации"

book_3696
- Не размеченная в эталоне сущность
  ORG <2081; 2086> "яндекс"

book_3688
- Ошибочная сущность в эталоне
  ORG <2573; 2573> ")"

book_3680
- Ошибочные сущности в эталоне
  ORG <731; 770> "пресс-службы "вконтакте" и роскомнадзора"
  ORG <1764; 1850> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube"
  ORG <1764; 1855> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube, ivi"
  ORG <1764; 1863> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube, ivi, zoomby"
  ORG <1764; 1871> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube, ivi, zoomby, megogo"
  ORG <1806; 1841> "соцсетей "одноклассники" и "мой мир""

book_3677
- Не размеченные в эталоне сущности
  ORG <180; 188> "интернете"
  ORG <8231; 8239> "интернете"

book_3667
- Ошибочные сущности в эталоне
  LOC <1991; 2107> "вологодской, тульской, ленинградской, тверской, новгородской, пензенской, амурской, псковской и белгородской областях"
  LOC <2004; 2107> "тульской, ленинградской, тверской, новгородской, пензенской, амурской, псковской и белгородской областях"
  LOC <2014; 2107> "ленинградской, тверской, новгородской, пензенской, амурской, псковской и белгородской областях"
  LOC <2029; 2107> "тверской, новгородской, пензенской, амурской, псковской и белгородской областях"
  LOC <2039; 2107> "новгородской, пензенской, амурской, псковской и белгородской областях"
  LOC <2053; 2107> "пензенской, амурской, псковской и белгородской областях"
  LOC <2065; 2107> "амурской, псковской и белгородской областях"
  LOC <2075; 2107> "псковской и белгородской областях"

book_3581
- Не размеченные в эталоне сущности
  ORG <1770; 1782> "гаврский порт"
  ORG <3219; 3233> "музее мормоттан

book_3983
- Описание компании ошибочно входит в сущность Росгеология
  ORG <407; 450> "госкомпании по геологоразведке — росгеология"
  ORG <4962; 5018> "государственной компании по геологоразведке — росгеология"

book_3982
- ЕС ошибочно помечен локацией, хотя это организация
  LOC <28; 29> "ес"
  LOC <67; 84> "европейского союза"
  LOC <768; 769> "ес"

book_3980
- Ошибочное вхождение слова «материнской» в сущность
  ORG <1538; 1557> "материнской tele2 ab"
- Организация ошибочно помечена как локация
  LOC <3096; 3105> "ростелеком"
  LOC <3217; 3229> ""ростелекома""
- Сущность не размечена в эталоне
  ORG <135; 137> "втб"

book_3978
- Неименованная сущность
  ORG <221; 252> "публичной нефтегазовой компанией"

book_3976
- Неименованная сущность
  ORG <391; 411> "голливудского гиганта"

bool_3972
- Организации ошибочно помечены локациями
  LOC <16; 51> "американская финансовая компания ice"
  LOC <352; 379> "франкфуртскую deutsche börse"
  LOC <1244; 1256> "nyse euronext"
- США не размечены как локация
  LOC <3392; 3394> "сша"
  LOC <3445; 3447> "сша"

book_3971
- Неименованная сущность
  ORG <167; 206> "российский телекоммуникационный оператор"
- Не размечена организация
  ORG <1024; 1056> "собрании акционеров "ростелекома""

book_3965
- В сущность ошибочно добавлено слово «финскую»
  ORG <117; 129> "финскую nokia"

book_3962
- Неименованная сущность
  ORG <191; 216> "камерный музыкальный театр"

book_3920
- Странная организация
  ORG <140; 214> "руководство востребованного у жителей нашей страны блог-сервиса livejournal"

book_3910
- Организации ошибочно помечены локациями
  LOC <1522; 1525> "обсе"
  LOC <1610; 1650> "украинского внешнеполитического ведомства"
  LOC <1774; 1775> "ес"
  LOC <2180; 2183> "обсе"
  LOC <3418; 3423> "кремле"

book_3904
- Описание компании ошибочно входит в сущность
  ORG <513; 544> "российского газового монополиста"
  ORG <180; 233> "российская государственная газовая монополия "газпром""

book_3890
- Ошибочная локация
  LOC <1580; 1593> "местном театре"

book_3889
- Ошибочные организации
  ORG <698; 712> "посевного фонда"
  ORG <1725; 1742> "отборочный комитет"
- Лишние слова в сущности
  ORG <636; 653> "microsoft в россии"

book_3888
- В данном тексте сколково выступает в роли организации, а размечено локацией
  LOC <648; 657> ""сколково""
  LOC <805; 814> ""сколково""

book_3887
- ЕС помечен как локация
  LOC <724; 741> "европейского союза"
  LOC <832; 848> "европейский союз""
  book_3886
- Штраф за описание организации
  ------STANDARD------
  0.33       ORG <128; 158> "китайским производителем xiaomi"              =             ORG <153; 158> "xiaomi"

book_3883
- В эталоне не размечены организации
  ORG <641; 643> "квн"
  ORG <1430; 1438> "интернете"

book_3882
- Неполное наименование сущности в эталоне
  ------STANDARD------
  0.67    ORG <220; 234> "савеловский суд"       =             ORG <220; 241> "савеловский суд москвы"

book_3881
- ЕС помечен как локация
  LOC <1389; 1390> "ес"

book_3880
- Организация помечена как локация
  LOC <920; 942> "пулковской обсерватории"

book_3860
- Неименованная сущность
  ORG <1024; 1055> "руководство газового монополиста"

book_3842
- Организация помечена как локация
  LOC <3238; 3241> "обсе"

book_3833
- Штраф за вложенную сущность
  --------TEST--------
  1.00    ORG <211; 234> "социальной сети facebook" =             ORG <211; 234> "социальной сети facebook"
  0.00 ORG <227; 234> "facebook"

book_3820
- ЕС помечен как локация
  LOC <779; 794> "европейский союз"
  LOC <1758; 1766> "евросоюза"
  LOC <1905; 1913> "евросоюза"
  LOC <1994; 1995> "ес"
- Ошибочная сущность
  LOC <1041; 1044> "суде"
- Не размеченная сущность
  ORG <1610; 1618> "bloomberg"

**Comment by vbocharov** [comment]
book_3811

Организации размечены как локации LOC <217; 228> "роскомнадзор" LOC <379; 391> "роскомнадзоре" LOC <477; 480> "раэк" LOC <1056; 1067> "роскомнадзор" LOC <1264; 1276> "роскомнадзора" LOC <3374; 3386> "роскомнадзоре" LOC <3641; 3652> "роскомнадзор"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/100

book_3809

Сущности не размечены в эталоне ORG <20; 30> "саммит нато" ORG <120; 131> "саммита нато" ORG <1333; 1343> "саммит нато" ORG <2113; 2124> "саммите нато"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/91
https://github.com/dialogue-evaluation/factRuEval-2016/issues/86
https://github.com/dialogue-evaluation/factRuEval-2016/issues/85

book_3801

США ошибочно помечена как организация ORG <3672; 3674> "сша"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/99

book_3799

Лишнее слово «британская» в сущности ORG <132; 154> "британская the guardian"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/98

book_3797

Роскосмос ошибочно помечен как локация LOC <1545; 1554> "роскосмоса"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/97

book_3796

Не размеченные в эталоне сущности ORG <1647; 1655> "интернете" ORG <2012; 2023> "коллегии фсб" ORG <2358; 2366> "интернете" ORG <3162; 3170> "интернета"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/96

book_3775

Не размеченные в эталоне сущности ORG <323; 331> "интернете"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/95

book_3774

Организация помечена как локация LOC <1219; 1232> "европарламенте"

см. https://github.com/dialogue-evaluation/factRuEval-2016/issues/94

book_3770

Неверные границы сущностей ------STANDARD------ 0.00 ORG <231; 233> "фнс" 0.00 ORG <269; 271> "фтс" 0.00 ORG <736; 738> "фас" 0.00 ORG <774; 776> "фст" --------TEST-------- 0.75 ORG <201; 234> "федеральной налоговой службы (фнс)" = ORG <201; 228> "федеральной налоговой службы" 0.75 ORG <238; 272> "федеральной таможенной службы (фтс)" = ORG <238; 266> "федеральной таможенной службы" 0.75 ORG <700; 739> "федеральной антимонопольной службы (фас)" = ORG <700; 733> "федеральной антимонопольной службы" 0.80 ORG <743; 777> "федеральной службы по тарифам (фст)" = ORG <743; 771> "федеральной службы по тарифам"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/93

book_3765

Не размеченные в эталоне сущности ORG <908; 918> "дизайн года" ORG <1260; 1278> "жюри "дизайна года"" ORG <1411; 1441> "судейской команды "дизайн года""

У первого упоминания (908, 918) совсем не организационный контекст. Остальные два отмечены.
см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/92

book_3764

Неверные границы сущности ------STANDARD------ 0.67 ORG <7; 25> ""большой восьмерки"" = ORG <0; 25> "саммит "большой восьмерки"" 0.67 ORG <151; 169> ""большой восьмерки"" = ORG <143; 169> "саммита "большой восьмерки"" 0.50 ORG <714; 715> "g8" = ORG <706; 715> "саммита g8" 0.50 ORG <892; 893> "g8" = ORG <885; 893> "саммит g8"
Организация помечена как локация LOC <719; 728> ""сколково"" LOC <897; 906> ""сколково""

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/91

book_3758

Ошибочная сущность в эталоне LOC <584; 608> "корея предложила северной"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/90

book_3757

Организация помечена как локация LOC <1586; 1587> "ес" LOC <2426; 2427> "ес"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/89

book_3746

Организации помечены как локации LOC <57; 58> "ес" LOC <217; 225> "евросоюза" LOC <317; 318> "ес" LOC <322; 325> "нато" LOC <567; 568> "ес" LOC <875; 883> "евросоюза" LOC <998; 999> "ес" LOC <1454; 1455> "ес" LOC <1572; 1579> "евросоюз"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/88

book_3744

Организации помечены как локации LOC <1208; 1216> "евросоюза" LOC <1581; 1582> "ес" LOC <1798; 1806> "евросоюзу" LOC <2283; 2290> "евросоюз" LOC <2395; 2396> "ес"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/87

book_3734

Неверные границы сущности ------STANDARD------ 0.80 ORG <546; 590> "международной организации гражданской авиации" = ORG <546; 597> "международной организации гражданской авиации (icao)"
Локации помечены как организации ORG <1840; 1856> "донецкой областью" ORG <3434; 3440> "донецке"
Не размеченные в эталоне сущности ORG <2398; 2408> "саммит g-20" ORG <4750; 4751> "ес" ORG <5221; 5228> "facebook"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/86

book_3714

Неверные границы сущности ------STANDARD------ 0.50 ORG <1386; 1387> "g7" = ORG <1378; 1387> "саммита g7" 0.50 ORG <2199; 2200> "g7" = ORG <2190; 2200> "саммитом g7" 0.50 ORG <2258; 2259> "g7" = ORG <2250; 2259> "саммита g7"
Организации помечены как локации LOC <2442; 2443> "ес"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/85

book_3702

Организации помечены как локации LOC <2007; 2008> "ес" LOC <2987; 2998> "еврокомиссии"
Не размеченная в эталоне сущность ORG <1209; 1258> "подразделения вооруженных сил российской федерации"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/84

book_3696

Не размеченная в эталоне сущность ORG <2081; 2086> "яндекс"

см. https://github.com/dialogue-evaluation/factRuEval-2016/issues/83

book_3688

Ошибочная сущность в эталоне ORG <2573; 2573> ")"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/82

book_3680

Ошибочные сущности в эталоне ORG <731; 770> "пресс-службы "вконтакте" и роскомнадзора" ORG <1764; 1850> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube" ORG <1764; 1855> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube, ivi" ORG <1764; 1863> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube, ivi, zoomby" ORG <1764; 1871> "интернет-компании mail.ru group (владелец соцсетей "одноклассники" и "мой мир"), rutube, ivi, zoomby, megogo" ORG <1806; 1841> "соцсетей "одноклассники" и "мой мир""

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/81

book_3677

Не размеченные в эталоне сущности ORG <180; 188> "интернете" ORG <8231; 8239> "интернете"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/79

book_3667

Ошибочные сущности в эталоне LOC <1991; 2107> "вологодской, тульской, ленинградской, тверской, новгородской, пензенской, амурской, псковской и белгородской областях" LOC <2004; 2107> "тульской, ленинградской, тверской, новгородской, пензенской, амурской, псковской и белгородской областях" LOC <2014; 2107> "ленинградской, тверской, новгородской, пензенской, амурской, псковской и белгородской областях" LOC <2029; 2107> "тверской, новгородской, пензенской, амурской, псковской и белгородской областях" LOC <2039; 2107> "новгородской, пензенской, амурской, псковской и белгородской областях" LOC <2053; 2107> "пензенской, амурской, псковской и белгородской областях" LOC <2065; 2107> "амурской, псковской и белгородской областях" LOC <2075; 2107> "псковской и белгородской областях"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/78

book_3581

Не размеченные в эталоне сущности ORG <1770; 1782> "гаврский порт" ORG <3219; 3233> "музее мормоттан

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/76

book_3983

Описание компании ошибочно входит в сущность Росгеология ORG <407; 450> "госкомпании по геологоразведке — росгеология" ORG <4962; 5018> "государственной компании по геологоразведке — росгеология"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/125

book_3982

ЕС ошибочно помечен локацией, хотя это организация LOC <28; 29> "ес" LOC <67; 84> "европейского союза" LOC <768; 769> "ес"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/124

book_3980

Ошибочное вхождение слова «материнской» в сущность ORG <1538; 1557> "материнской tele2 ab"
Организация ошибочно помечена как локация LOC <3096; 3105> "ростелеком" LOC <3217; 3229> ""ростелекома""
Сущность не размечена в эталоне ORG <135; 137> "втб"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/123

book_3978

Неименованная сущность ORG <221; 252> "публичной нефтегазовой компанией"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/122

book_3976

Неименованная сущность ORG <391; 411> "голливудского гиганта"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/120

bool_3972

Организации ошибочно помечены локациями LOC <16; 51> "американская финансовая компания ice" LOC <352; 379> "франкфуртскую deutsche börse" LOC <1244; 1256> "nyse euronext"
США не размечены как локация LOC <3392; 3394> "сша" LOC <3445; 3447> "сша"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/56

book_3971

Неименованная сущность ORG <167; 206> "российский телекоммуникационный оператор"
Не размечена организация ORG <1024; 1056> "собрании акционеров "ростелекома""

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/129

book_3965

В сущность ошибочно добавлено слово «финскую» ORG <117; 129> "финскую nokia"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/117

book_3962

Неименованная сущность ORG <191; 216> "камерный музыкальный театр"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/130

book_3920

Странная организация ORG <140; 214> "руководство востребованного у жителей нашей страны блог-сервиса livejournal"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/116

book_3910

Организации ошибочно помечены локациями LOC <1522; 1525> "обсе" LOC <1610; 1650> "украинского внешнеполитического ведомства" LOC <1774; 1775> "ес" LOC <2180; 2183> "обсе" LOC <3418; 3423> "кремле"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/114

book_3904

Описание компании ошибочно входит в сущность ORG <513; 544> "российского газового монополиста" ORG <180; 233> "российская государственная газовая монополия "газпром""

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/113

book_3890

Ошибочная локация LOC <1580; 1593> "местном театре"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/112

book_3889

Ошибочные организации ORG <698; 712> "посевного фонда" ORG <1725; 1742> "отборочный комитет"
Лишние слова в сущности ORG <636; 653> "microsoft в россии"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/111

book_3888

В данном тексте сколково выступает в роли организации, а размечено локацией LOC <648; 657> ""сколково"" LOC <805; 814> ""сколково""

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/110

book_3887

ЕС помечен как локация LOC <724; 741> "европейского союза" LOC <832; 848> "европейский союз""

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/109

book_3886
Штраф за описание организации ------STANDARD------ 0.33 ORG <128; 158> "китайским производителем xiaomi" = ORG <153; 158> "xiaomi"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/108

book_3883

В эталоне не размечены организации ORG <641; 643> "квн" ORG <1430; 1438> "интернете"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/107

book_3882

Неполное наименование сущности в эталоне ------STANDARD------ 0.67 ORG <220; 234> "савеловский суд" = ORG <220; 241> "савеловский суд москвы"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/106

book_3881

ЕС помечен как локация LOC <1389; 1390> "ес"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/105

book_3880

Организация помечена как локация LOC <920; 942> "пулковской обсерватории"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/104

book_3860

Неименованная сущность ORG <1024; 1055> "руководство газового монополиста"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/103

book_3842

Организация помечена как локация LOC <3238; 3241> "обсе"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/102

book_3833

Штраф за вложенную сущность --------TEST-------- 1.00 ORG <211; 234> "социальной сети facebook" = ORG <211; 234> "социальной сети facebook" 0.00 ORG <227; 234> "facebook"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/131

book_3820

ЕС помечен как локация LOC <779; 794> "европейский союз" LOC <1758; 1766> "евросоюза" LOC <1905; 1913> "евросоюза" LOC <1994; 1995> "ес"
Ошибочная сущность LOC <1041; 1044> "суде"
Не размеченная сущность ORG <1610; 1618> "bloomberg"

см.
https://github.com/dialogue-evaluation/factRuEval-2016/issues/101
