### ISSUE TITLE
пустой book_1667.objects

### ISSUE THREAD

**Issue by kzn** [dialogue-evaluation/factRuEval-2016#13]

**Comment by kzn** [comment]
В book_323.objects Есть персона 
13784 Person 27976 27977 27978 # основатель Джон Килинг
это допустимо?

**Comment by kzn** [comment]
В book_398.txt "«Это было самое тяжёлое решение на посту главного тренера сборной», сказал Клинсман." "Клинсман" - не отмечен как персона.

**Comment by vbocharov** [comment]
book_1667 - баг интерфейса разметки. По идее, он не должен был экспортироваться, т.к. он не готов. 

book_323 - ошибка в разметке. Такого быть не должно. Исправил.

book_398 - исправил.

Через минут десять закомичу.
Спасибо!
