### ISSUE TITLE
3591. Клуб католической интеллигенции 

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#142]
Test:

> 0.00 ORG [name : клуб католической интеллигенции (klub inteligencji katolickiej)]

Почему не засчиталась сущность?

**Comment by StanDzh** [comment]
У компаратора нет оснований для того, чтобы сопоставить эту сущность и эталонную. Эталон выглядит следующим образом:

```
3697 53487 53490 53494
descriptor клуб
name Klub Inteligencji Katolickiej
name Клуб католической интеллигенции
```

Соответственно, приведенный вариант имени сущности не является корректным нормализованным именем. Если мы хотим его засчитывать, то в эталон нужно добавить строку _name Клуб католической интеллигенции (Klub Inteligencji Katolickiej)_, но, по-моему, это все же не очень правильно.

@vbocharov, как сделаем?
