### ISSUE TITLE
3602. Минюст 

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#145]
Standard:

> 1.00  ORG [name : минюст министерство | министерство юстиции | министерство минюст | минюст] =   ORG [name : министерство юстиции]

Test:

> 0.00 ORG [name : минюст]

Кажется, что должно было засчитаться

**Comment by StanDzh** [comment]
Эта ситуация аналогична #150, оценка корректна и обоснована тем, что для одной сущности в эталоне выделены две в тесте.
