### ISSUE TITLE
3615. Васюки

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#150]
Test:

> 1.00  LOC [name : васюки]   =   LOC [name : нью - васюки | васюки]
> 0.00 LOC [name : нью-васюки]

Как такое может быть одновременно?

**Comment by StanDzh** [comment]
Если я правильно понимаю вопрос, то это вполне корректная оценка, т.к. вместо одной сущности были выделены две.

Или речь шла про то, почему в эталоне эти упоминания объединены в одну сущность?

**Comment by AndreyAv** [comment]
почему в эталоне эти упоминания объединены в одну сущность? По тексту - два разных объекта.
