### ISSUE TITLE
3626. Суд лос-анджелеса

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#151]
В разметке не выделена сущность

> 0.00 ORG [name : суд лос-анджелеса]

**Comment by vbocharov** [comment]
Номер 2954. Была недовыделена.

**Comment by StanDzh** [comment]
можно ли тогда считать эту сущность именованной и проставить у нее name вместо дескриптора? Сейчас она неотличима от просто 'суд'.
