### ISSUE TITLE
3644. Госдеп

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#154]
Test:

> 0.00 ORG [name : американский госдепартамент]
>    0.00 ORG [name : госдеп]

Кажется, неправильно, что нет таких сущностей

**Comment by vbocharov** [comment]
У сущности номер 2869.

**Comment by StanDzh** [comment]
Ситуация аналогична #159, поправлю эталон аналогичным образом:

```
2869 53227 53265
name американский госдепартамент
name госдеп
descriptor госдепартамент
```
