### ISSUE TITLE
3581. Парижская Третьяковка

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#157]
Test:

> 0.00 ORG [name : парижская третьяковка]

Почему не засчиталось?

**Comment by StanDzh** [comment]
Из эталона:

```
3527 53546 53549 53550
descriptor музей
descriptor парижская Третьяковка
name Орсе
name музей Орсе
```

У компаратора нет оснований считать, что "парижская Третьяковка"  - это корректное название организации, т.к. эта фраза помечена как дескриптор. С другой стороны, это явно какой-то некорректный дескриптор. По-моему, нужно либо проставить это как имя - если мы хотим, чтобы сущность засчитывалась - либо убрать вообще, тогда сущность засчитываться не будет.

Поправлю эталон в следующем коммите, чтобы 'парижская Третьяковка' была именем этой сущности.
