### ISSUE TITLE
3581. английский парламент

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#159]
Test:

> 0.00 ORG [name : английский парламент]

Почему не засчиталось?

**Comment by vbocharov** [comment]
Объект есть (3556). Стас?

**Comment by StanDzh** [comment]
Не засчиталось потому, что этот объект не имеет ни одного имени. Для компаратора в этой ситуации 'английский парламент' попал в ту же категорию, что и различные просто 'компании' и 'министрества', и был жестко исключен из сравнения. Так что эта оценка при таком эталоне представляется вполне корректной.

Edit: только что заметил, что эталон уже подправлен

**Comment by StanDzh** [comment]
Больше эта ошибка не воспроизводится, добавил тест
