### ISSUE TITLE
Как компаратор объясняет свои оценки

### ISSUE THREAD

**Issue by KingOfLing** [dialogue-evaluation/factRuEval-2016#16]
В выдаче компаратора я обнаружил только несколько столибов с цифрами на консоли (кстати, что есть три последние столбца - TP, In Std.,  In Test?)
Очевидно, что компаратор должен объяснять свои оценки - выдавать информацию о всех совпадениях-различиях и их весах, на основании которых вычислены оценки, иначе невозмножны ни настройка системы на особенности вычисления оценки, ни верификация полученных оценок ни их анализ?!  
Александр Ермаков, ЭР СИ О

**Comment by StanDzh** [comment]
Здравствуйте.

TP - это True Positive, суммарная оценка совпадения эталона с тестом - то, то попадает в числитель при подсчете точности и полноты
In Std. - это общее количество объектов в эталоне
In Test - количество объектов в тесте (за исключением тех, которые не участвуют в сравнении, например - вложенные организации при угаданной объемлющей)

Как раз на основе этих трех чисел и вычисляются общие оценки. Опишите, пожалуйста, подробнее, какого рода вывод Вам хотелось бы видеть - и я попробую его реализовать. Для каждого тестового объекта - то, с чем он сопоставился, и насколько хорошо - правильно я понимаю? И, видимо, что-то аналогичное для эталонных объектов?

**Comment by KingOfLing** [comment]
Здравствуйте!
1) Если TP - это True Positive (что я и предполагал), то почему это не целое число - количество тех выделенных системой упоминаний объектов, которые совпали с эталонными?
2) Вы правильно понимаете: "Для каждого тестового объекта - то, с чем он сопоставился (АЕ: или не сопоставился), и насколько хорошо". 
Пожелания к минимально простому выводу я постараюсь сформулировать сегодня...

**Comment by KingOfLing** [comment]
Желаемый протокол сравнения по Дорожке 1 - два текстовых таб-делимитед файла: 

Файл 1. Данные о всех выделенных тестовых объектах - для каждого объекта новой строкой тип+оффсет+длина с указанием сопоставленного объекта 
(если таковой найден компаратором) - его тип+оффсет+длина и стоит  выдернуть текстовую строку эталонного объекта (т.к. никакой иллюстративной информации-комментариев в формате результатов тестовых объектов, к сожалению не предусмотрено) 
дабы протокол можно было сразу интерпретировать без последующей программной обработки.
Скажем, так:
1.0 book_132.txt    ORG 95 10       LOC_ORG 95 10   Майкрософт    // полное совпадение с весом 1
0,9 book_128.txt    ORG 240 9       ORG 240 14  Microsoft Inc.  // частичное совпадение с весом 0,9
0   book_128.txt    LOC  320 38                                 // выделенный тестовый объект не совпадает с эталонными

Файл 2. Данные о всех эталонных объектах - в том же формате наоборот:
1.0 book_132.txt    LOC_ORG 95 10   ORG 95 10   Майкрософт    // полное совпадение с весом 1
0,9 book_128.txt    ORG 240 14      ORG 240 9   Microsoft Inc.  // частичное совпадение с весом 0,9
0   book_128.txt                    PER 426 10  Билл Гейтс         // эталонный объектом не совпадает с тестовыми
