### ISSUE TITLE
3687. театр дружбы народов

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#165]
Standard:

> **1.00** ORG [name : государственный театр наций | театр дружбы народов государственный театр | государственный театр театр наций | театр наций государственный театр | государственный театр театр дружбы народов | **театр дружбы народов** | театр наций] =   ORG [name : государственный театр наций]

Test:

> **1.00**   ORG [name : государственный театр наций]  =   ORG [name : государственный театр наций | театр дружбы народов государственный театр | государственный театр театр наций | театр наций государственный театр | государственный театр театр дружбы народов | **театр дружбы народов** | театр наций]
> 
> **0.00** ORG [name : **театр дружбы народов**]

Как так получается? см выделенное

**Comment by StanDzh** [comment]
Тут ситуация аналогичная #145 и #150 - две организации в тесте, которым соответствует одна организация в эталоне:

```
2697 53063 53067 53068 53070 53081 53082 53084 53090 53093 53108 53109 53110 53111 53112 53130
descriptor государственный театр
descriptor театр
name Государственный Театр Наций
name Театр Дружбы Народов
name Театр Наций
```

Так как все сопоставления делаются один-к-одному, при таком эталоне оценка корректна; эталон, вроде, тоже правильный. Или его тут нужно поправить, подскажи, плиз, @vbocharov?

**Comment by vbocharov** [comment]
Здесь два названия одного объекта. Такие случаи во всех остальных местах мы должны были объединить. Тут, вероятно, тоже.
