### ISSUE TITLE
3801. А.Н. Чилингаров

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#166]
Standard:

> 0.33  PER [patronymic : н, firstname : а, lastname : чилингаров]  =   PER [lastname : чилингаров, firstname : артур]

Test:

> 0.33  PER [lastname : чилингаров, firstname : артур]   =   PER [patronymic : н, firstname : а, lastname : чилингаров]

В тексте есть Артур Чилингаров, есть А.Н. Чилингаров. По идее самое правильное, это имя = Артур, отчество = Н, Фамилия = Чилингаров. Т.е. д.б. 0,67, разве нет?

**Comment by StanDzh** [comment]
Тут в разметке не хватает имени Артур, хотя в тексте оно действитльно есть. Можем мы ее добавить?
