### ISSUE TITLE
3734. интернациональная комиссия

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#169]
Standard:

> 0.00 ORG [name : интернациональная комиссия]

Это нарицательное. Контекст:

> и соответствующей интернациональной комиссии

**Comment by vbocharov** [comment]
Там два тега org_descr. По идее, не должна быть обязательной.
@StanDzh всё так?

**Comment by StanDzh** [comment]
Она и не является обязательной, по крайней мере в текущей версии компаратора. Видимо, это уже было поправлено:

```
------STANDARD------

IGNORED ORG [name : интернациональная комиссия]


--------TEST--------



-------METRICS------
Type    P        R        F1       TP1      TP2      In Std.  In Test.
PER        1.0000   1.0000   1.0000     0.00     0.00        0        0
LOC        1.0000   1.0000   1.0000     0.00     0.00        0        0
ORG        1.0000   1.0000   1.0000     0.00     0.00        0        0
OVERALL    1.0000   1.0000   1.0000     0.00     0.00        0        0
```

Подозреваю, что она и тогда не учитывалась, просто в выводе не писалось явно 'IGNORED'.
На всякий случай добавлю тест в следующий коммит
