### ISSUE TITLE
3762. правительство новгородской области

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#170]
Test:

> 0.00 ORG [name : правительство новгородской области]

Не выделена сущность в Standard

**Comment by vbocharov** [comment]
У неё номер 3895. Пропущенных не вижу. Проверьте, пожалуйста, ещё раз. Если найдёте пропущенную, то скопируйте текст предложения.

**Comment by AndreyAv** [comment]
Да, в coref сущность вижу, но, тем не менее, при оценке получаем в Test:

> 0.00 ORG [name : правительство новгородской области]

**Comment by AndreyAv** [comment]
Есть ли какое-то решение этого вопроса?
