### ISSUE TITLE
Нормализация

### ISSUE THREAD

**Issue by yu-lia** [dialogue-evaluation/factRuEval-2016#21]
Добрый день! Не очень понятна логика в порядке имён и фамилий для персон. Из инструкции можно подумать, что порядок должен быть сохранён как в тексте, однако в примерах иногда порядок непредсказуемо меняется, например:

В этот же день президент США Барак Обама заявил, что страна и народ до сих пор скорбят и не могут оправиться от шока, вызванного тем, что произошло в субботу. 

124-2 Occupation
Person obj122 **Обама Барак**
Job span22937 президент
Company obj116 США

1 февраля на ступеньках будущего президентского центра наследия возле бизнес-центра «Демидов» открылся памятник первому президенту России Борису Николаевичу Ельцину. 

253-0 Occupation
Person obj292 **Николаевич Борис Ельцин**
Job span33777 президенту
Company obj296 РФ

Кроме того, не всегда понятны принципы нормализации или её отсутствия:

259-11 Occupation
Person obj324 Майклсон Виктор
Job span27560 **зав .**
Company obj323 кафедра социальных коммуникаций и технологий РГГУ

В церемонии также приняли участие вдова Ельцина Наина Иосифовна, его друзья, представители федеральной власти, глава Свердловской области Александр Мишарин, руководители соседних регионов.

253-3 Occupation
Person obj310 Мишарин Александр
Job span33785 **губернатора** | span33825 **глава**
Company obj298 Свердловская область

Поясните, пожалуйста! 

Спасибо!

**Comment by vbocharov** [comment]
В *.facts текстовые значения можно игнорировать, т.к. компаратор смотрит не на них, а на идентификаторы объектов и спанов. Текстовые значения нужны в трёх случаях:
1. они отображаются в интерфейсе разметки фактов (он не видит базы, а видит только эти файлы с гита)
2. они помогают при чтении файла 
3. (теоретически) в качестве поля может быть текстовая строка, которой не было в тексте. В соревновании такого случиться не должно бы.
