### ISSUE TITLE
компаратор для 3 дорожки

### ISSUE THREAD

**Issue by named-entity** [dialogue-evaluation/factRuEval-2016#27]
Добрый день!

Несколько вопросов по оценке результатов третьей дорожки:
1. В описании формата выдачи для фактов Occupation одним из полей было Job. В файлах .facts это Position. Что всё же правильно?
2. Т.н. нормализованные имена в полях фактов записываются непоследовательно, и это влияет на сравнение. Например (из подробной выдачи в *.report.txt),
0.43    0.43    1.00    [ occupation | who : миллер алексей | position : глава | where : газпром ] =   [ occupation | job : глава | person : миллер алексей | where : оао газпром ](поле where заполнено коротким названием)
0.43    0.43    1.00    [ occupation | who : ху цзиньтао | position : председателя | where : китай ] =   [ occupation | job : председатель | person : цзиньтао ху | where : кнр ](поле where заполнено, видимо, одним из равноправных названий)
0.43    0.43    1.00    [ occupation | who : эдуард | position : президентов | where : michelin ]  =   [ occupation | job : президент | person : мишлен эдуард | where : группа компаний michelin ](поле заполнено названием без дескриптора)
Объясните, пожалуйста, как в таких случаях действует компаратор. Сравниваются ли хотя бы разные варианты имен одной сущности?
3. Что показывают оценки Q_A и Q_Id в файлах .report.txt?

**Comment by vbocharov** [comment]
1. Position

На остальные вопросы прошу ответить @StanDzh

**Comment by StanDzh** [comment]
3 - Q_a - это качество извлечения аттрибутов факта, Q_Id - это качество "идентификации", т.е. насколько хорошо корректно выделенные аттрибуты были соотнесены друг с другом (нужно для оценки неполных дубликатов фактов, если такие есть в тесте).

По поводу 2 - а какой это документ? Порядок полей firstname/lastname/etc. в нормализованных именах персон проверяется с учетом перестановок, в Вашем примере, кажется, дело скорее в организациях (и position/job). Попробую переделать вывод так, чтобы было более понятно, какие аттрибуты были выделены некорректно.

Насчет организаций - возможно, там не все имена из .coref-файлов перебираются, хотя должны. Проверю и поправлю, если так. Можно попросить вашу тестовую разметку для этого документа, чтобы руками не воссоздавать её при отладке?

**Comment by named-entity** [comment]
Спасибо!

115
Occupation
Job: ПРЕДСЕДАТЕЛЬ
Person: ЦЗИНЬТАО ХУ
Where: КНР

374
Occupation
Job: ГЛАВА
Person: МИЛЛЕР АЛЕКСЕЙ
Where: ОАО ГАЗПРОМ

145
Occupation
Job: ПРЕЗИДЕНТ
Person: МИШЛЕН ЭДУАРД
Where: ГРУППА КОМПАНИЙ MICHELIN

**Comment by vbocharov** [comment]
@named-entity 
Катя, всё ок?
Если да, то закрой тикет, пожалуйста.

**Comment by named-entity** [comment]
Стас обещал изменить вывод, чтобы было понятно, где ошибки в атрибутах. Мы пока не дождались.

**Comment by named-entity** [comment]
Спасибо, стало лучше!
