### ISSUE TITLE
Экстралингвистическая информация

### ISSUE THREAD

**Issue by yu-lia** [dialogue-evaluation/factRuEval-2016#28]
Добрый день! В некоторых фактах встречаются случаи, когда поля фактов заполняются на основании информации, не содержащейся в том же предложении или тексте, например:

29 апреля 2011 года Адриано Челентано, известный певец, актёр и общественный деятель, написал письмо в газету Fatto Quotidiano, в котором достаточно резко раскритиковал премьер-министра Сильвио Берлускони и обвинил его во лжи, заявив, что Берлускони не способен управлять большой страной. Также, в своём письме Челентано призвал итальянцев принять участие в референдуме, который должен состояться на Апеннинах 12 июня (документ 271),

[ occupation | who : берлускони сильвио | position : премьер-министра | where : апеннины | италия ]   

Встретилось несколько таких вариантов разбора. Ошибка в разметке?

Спасибо!

**Comment by yu-lia** [comment]
простите, вставила неудачный пример, сейчас отредактирую текст

**Comment by Shnurre** [comment]
Не могли бы Вы написать какой это номер текста?(271 это текст с Вашим прошлым примером)
Впрочем, я считаю, что на фрагменте, который Вы привели факт выделяться должен. Да страна упоминается анафорически, но однозначно(итальянцев, на Аппенинах).
Другое дело, что должна стоять повышенная сложность. Скажите мне, пожалуйста, номер текста и я ее проставлю, если она еще не стоит

**Comment by yu-lia** [comment]
Да, извините, не поменяла, это текст 295.

**Comment by Shnurre** [comment]
Спасибо, добавил повышенную сложность
