### ISSUE TITLE
Ошибки разметки 2 дорожки

### ISSUE THREAD

**Issue by mariarusia** [dialogue-evaluation/factRuEval-2016#34]
book_74.coref 

Дмитрий записан с опечаткой - ДмитИрий. 
Ошибка переползает и в третью дорожку

**Comment by konstantin-smith** [comment]
Проясните, пожалуйста, насчёт 3-х частных азиатских имён. В тексте 1667 (больше азиаты вроде нигде не встречаются) все они теряют последнюю часть. Например, "Ким Чен Ир" - lastname:Ким firstname:Чен.  Это правильно? А как должно быть (точнее, как чаще размечается в больной выборке)?
А в 498 с бедной "Аун Сан Су Чжи" вообще обошлись по-варварски, оставив только firstname: Аун Сан (хотя это фамилия, вроде).  Как там в "большой выборке"?

**Comment by vbocharov** [comment]
@mariarusia fixed (жди коммита)

@konstantin-smith 

Тут всё не случайно, т.к. про них думали. В эталоне должно быть вот так:

lastname: Ким
firstname: Чен
firstname1: Ир

Поля с номером означают, что это не альтернативное написание предыдущего, а ещё одно поле. Анна / Аннушка была бы записана вот так:

firstname: Анна
firstname: Аннушка

Компаратор должен понимать такие записи.

Решения о том, где имя, а где фамилия, основаны на этой статье: https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D0%B5%D0%B9%D1%81%D0%BA%D0%BE%D0%B5_%D0%B8%D0%BC%D1%8F

с Аун Сан Су Чжи всё иначе, т.к. там нет фамилии, если верить Википедии:

«Аун Сан» — имя отца, «Су» — имя бабушки, Чжи — часть имени матери, Кхи Чжи . Добавление имени родителей довольно распространено, но добавленное имя в таком случае не является фамилией или отчеством.

https://ru.wikipedia.org/wiki/%D0%91%D0%B8%D1%80%D0%BC%D0%B0%D0%BD%D1%81%D0%BA%D0%BE%D0%B5_%D0%B8%D0%BC%D1%8F
Поэтому каждый кусок, пришедший от кого-то одного, размечен как firstname.

**Comment by konstantin-smith** [comment]
Понятно, жаль, что это отсутствовало в документации. Выяснилось, что есть не только firstname1, но и firstname2 и lastname1.  Кстати, в примере 154 для "Ирина Саишвили-Чантурия" составная фамилия разнесена по lastname и lastname1. Так и должно быть, или это ошибка? Спрашиваю потому,  что выборка devset маленькая, и по ней трудно делать выводы о редких случаях.

**Comment by konstantin-smith** [comment]
Также прошу прояснить вопрос об Интернете - в половине случаев он считается Org, в половине игнорируется. А также заодно о Wikipedia, YouTube, Skype, Рунет - это организации или нет? Спасибо.

**Comment by vbocharov** [comment]
@konstantin-smith 

Про нумерованные атрибуты: этого нет в документации, т.к. простановка таких атрибутов не является задачей участников. Формат, ожидаемый от участников, меняется гораздо меньше (почти не меняется), чем формат эталона. Но вместе с форматом эталона меняется и компаратор. Но тут я не знаю, как он себя ведёт, поэтому задал вопрос @StanDzh . Жду ответа.

Интернет и Рунет по инструкции (той, что по разметке) должны быть организациями. Это не очень хорошее решение, но оно уже есть, поэтому не меняем. Про остальное - посмотрю на контексты. Если написано "директор Skype", "отдел Skype", "Skype приобрёл", то Skype - это организация. Если "позвонил по Skype", то нет. Ошибки поправлю.

**Comment by vbocharov** [comment]
Ошибки поправил.
