### ISSUE TITLE
Третья дорожка

### ISSUE THREAD

**Issue by mariarusia** [dialogue-evaluation/factRuEval-2016#35]
1 124-0 Occupation 
2 Who obj118 Гиффордс Гэбриэль 
3 Position span22925 член 
4 Where obj121 Палаты представителей Конгресса США 
5 

6 124-1 isPartOf 
7 Company obj121 Палаты представителей Конгресса США 
8 Company obj115 Конгресса США 

В 124 тексте у компании неправильное нормализованное имя: "ПалатЫ" вместо "Палата". Во второй дорожке такой ошибки нет.

**Comment by Shnurre** [comment]
Спасибо, исправил
