### ISSUE TITLE
Неконсистентная токенизация в devset

### ISSUE THREAD

**Issue by grossws** [dialogue-evaluation/factRuEval-2016#36]
Например, в 282 `Абу-Грейв` -- один токен, а в 367 `Жан-Мари` -- три токена.

**Comment by vbocharov** [comment]
Почему вы считаете, что это неверно?

**Comment by grossws** [comment]
А почему одинаковые по структуре слова должны токенизироваться по-разному? Или это способ ещё ухудшить и без того плохую ситуацию для обучения на 122 (sic!) документах?

**Comment by vbocharov** [comment]
Это разные ситуации:

Жан-Мари - это два отдельных имени у одного человека. Разделены, т.к. каждое должно быть разобрано на уровне морфологии по словарю.

Абу-Грейв - с точки зрения русского языка делить бессмысленно, т.к. эти слова по отдельности имеют значение только в том языке, из которого пришло название этого населённого пункта.

Закрываю, т.к. токенизация не влияет напрямую на соревнование.

В тикете https://github.com/dialogue-evaluation/factRuEval-2016/issues/118 дана ссылка на документацию по соревнованию, которая регламентирует разметку нескольких имён у персон.
