### ISSUE TITLE
TestSet. Имена файлов

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#45]
Правильно ли я понимаю, что в размеченном тестсете и в большом наборе для соревнования имена файлов отличаются? То есть, чтобы проверить свою собственную разметку по каждому прогону нужно сначала найти соответствия между текстовыми файлами, одинаковыми по содержанию, а затем переименовать все соотвествующие файлы *.task* ?

**Comment by vbocharov** [comment]
Можно сделать две вещи:
- обработать заново тестсет в том виде, в котором я его выложил

или
- переименовать файлы из вашего старого прогона по таблице соответствия (её выложу сейчас)

**Comment by vbocharov** [comment]
файл testset/list.txt:

в первой колонке - имя файла в тестовой выборке
во второй колонке - имя файла в эталоне (в папке testset)

**Comment by AndreyAv** [comment]
Спасибо!
