### ISSUE TITLE
TestSet. Выделяется лишняя сущность США

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#46]
Файлы **book_3980, book_3979, book_3978, book_3977, book_3976, book_3974, book_3973**.
**LOC [name : сша]**: Не должна выделяться такая сущность. США упоминается только в словосочетании _доллары США_ .  Более того, в аналогичной ситуации в демо-сете _США_ не выделяется в отдельную сущность из сущности _ВВС США_ (см. файл **book_93.txt** демо-сета)

**Comment by vbocharov** [comment]
Правила не требовали невыделения в этом случае. В демо скорее ошибка.
Но да, я согласен с тем, что выделение не несёт смысла.
