### ISSUE TITLE
book_3980. Ростелеком

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#47]
LOC [name : "ростелеком"]: правильно не LOC, а ORG

**Comment by vbocharov** [comment]
Укажите, пожалуйста, которое вхождение слова вы имеете ввиду.

**Comment by AndreyAv** [comment]
Все три вхождения

**Comment by vbocharov** [comment]
Похоже, что исправлено:

$ grep -i "ростеле" book_3980.objects 
47086 Org 78424 # Ростелеком
47108 Org 78452 # Ростелеком
47112 Org 78458 # Ростелекома
47131 Org 78477 # Ростелекомом
