### ISSUE TITLE
TestSet. Интернет, рунет: не организации

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#48]
Исходя из определения (Если Х может быть местом работы человека или в ней можно состоять в качестве члена, то Х — это организация. Организации, членами которых являются страны или другие организации, тоже засчитываются) рунет – не организация, так же, как и интернет.
Противоречие с этим есть в разметках файлов **book_3979, book_3757, book_3677**. При этом, во многих других случаях _интернет_ в качестве сущности не выделяется, что, на наш взгляд, правильно.

**Comment by vbocharov** [comment]
Закрываю, т.к. уже обсуждалось тут:
https://github.com/dialogue-evaluation/factRuEval-2016/issues/95
