### ISSUE TITLE
book_3983. Объединение сущностей

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#50]
1. _PER [patronymic : владимирович, lastname : путин, firstname : владимир]_: здесь нельзя однозначно определить, что «Владимирович» относится к Путину
2. _PER [patronymic : ефимович, lastname : донской, firstname : сергей]_: аналогично – неоднозначно, что «Ефимович» относится к Донскому

**Comment by vbocharov** [comment]
Почему?
