### ISSUE TITLE
book_3539

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#51]
По этому файлу вопросы объединю в один issue, дабы не плодить темы:
1. PER [lastname : смирнов, lastname : сокольский]: разве не правильнее будет PER [lastname : смирнов-сокольский]
2. PER [firstname : мая]: правильно – «май»
3. 0.00 PER [firstname : евгения, patronymic : степановна]: почему не защитано? Однозначно сопоставить Евгению Степановну и Евгению Скалацкую нельзя
4. 0.00 PER [firstname : николай, patronymic : петрович]: аналогично не сопоставить Николая Петровича и Николая Вертинского
5. 0.00 PER [lastname : ли]: почему не защитано? Вот фрагмент текста: <…>китайчат Ли<…>
6. 0.00 LOC [name : китеж]: есть такая сущность
7. 0.00 ORG [name : армия колчака]: есть такая сущность
8. 0.00 ORG [name : гастрольбюро]: есть такая сущность
9. ORG [name : астория]: есть такая сущность. Фрагмент текста: 

> Он находился в своем 208-м номере «Астории».

Не понятно, почему в разметке _Астория_ ставится в соответствие _Австрии_

**Comment by vbocharov** [comment]
1. двойные имена и фамилии нужно было разделять (см. https://github.com/dialogue-evaluation/factRuEval-2016/issues/118)
2. исправлено
3. см. следующий
4. я исхожу из того, что человеку, читающему этот текст, очевидно, что это одна и та же персона.
5. это группа людей, а не одна персона
6. добавил
7. добавил
8. добавил
9. и в эталоне она тоже есть. Выношу в отдельный тикет https://github.com/dialogue-evaluation/factRuEval-2016/issues/132
