### ISSUE TITLE
TestSet. НЕименованные сущености

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#52]
book_3980
ORG [name : правление банка], ORG [name : совет директоров госоператора]
book_3979
ORG [name : совет директоров компании] 
Все это - неименованные сущности, соответственно, не должны выделяться как организации. 
Обсуждение этого вопроса на примерах devset'а уже было (см. issue Нарицательные в разметке #17)

**Comment by vbocharov** [comment]
исправил в эталоне

**Comment by AndreyAv** [comment]
Leave a comment
