### ISSUE TITLE
book_3976. Walt Disney

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#54]
Walt Disney – не ассоциируется с Walt Disney Company, а выделяется в отдельную сущность персоны. Предложение, где Walt Disney – персона:  

> Walt Disney приобрела Lucasfilm и снимет седьмой эпизод «Звёздных войн»
> 0.00 PER [lastname : disney, firstname : walt]

Ошибочное выделение персоны в разметке.

**Comment by vbocharov** [comment]
Это правильная разметка эталона. Компаратор должен был без штрафа принять как выделение так и не выделение такой персоны. Он сейчас за это штрафует?

**Comment by AndreyAv** [comment]
Штрафует за невыделение этой персоны

**Comment by vbocharov** [comment]
attn @StanDzh

**Comment by StanDzh** [comment]
Поправил в последнем коммите
