### ISSUE TITLE
book_3974. Лишняя сущность

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#55]
В разметке выделена сущность

> 0.00 LOC [name : россия]

При том, что в тексте нет ни России, ни РФ и т.п.

**Comment by vbocharov** [comment]
Там несколько таких сущностей: 3378 (Россия), 3379 (Британия). 

Это сущности (Loc или LocOrg), сделанные из прилагательных (тег geo_adj). Они нужны фактам и не должны участвовать в первой и второй дорожках. Поскольку они нужны фактам, то отмечены только в тех местах, где нужны для какой-то валентности. Т.е. неконсистентно.

Если они, действительно, участвуют в оценке первой и второй дорожек, то нужно внести изменения в компаратор: игнорировть (совсем, т.е. даже штрафовать за их наличие у участников соревнования) объекты второго и третьего слоя разметки, созданные только из geo_adj.

@StanDzh , ты понимаешь, про что я?

**Comment by mariarusia** [comment]
Есть подозрение, что штрафуют за выделение дескрипторов во второй дорожке
 3555 текст

Эталон
3584 52742
descriptor Киевский политех
descriptor политех

В результатах сравнения "выделение Киевского политеха" оштрафовано как лишнее.

Второй пример
3754
3047 53399 53414
descriptor МИД
descriptor МИД Азербайджана

**Comment by StanDzh** [comment]
@vbocharov Сделал по аналогии с остальными игнорируемыми при сравнении объектами, сейчас допишу тесты и залью

По поводу дескрипторов: Киевский Политех - это точно дескриптор?
(book_3555.spans)
87618 org_name 470 17 1765960 2  # 1765960 1765961 Киевском политехе

Сейчас посмотрю, чем вызвана вторая проблема

**Comment by vbocharov** [comment]
@mariarusia заводи, пожалуйста, отдельный тикет на каждую проблему. Иначе непонятно, когда текущий можно будет закрывать.

**Comment by StanDzh** [comment]
По вопросу @AndreyAv я уже влил правки в основную ветку, наверное, можно закрывать этот вопрос
