### ISSUE TITLE
book_3972. Не правильно выделились некоторые сущности

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#56]
0.00 ORG [name : nyse euronext]
   0.00 ORG [name : франкфуртская deutsche börse]

В разметке это почему-то локации

**Comment by vbocharov** [comment]
Это какая дорожка и какие аргументы компаратора?

В разметке сейчас вот так:

$ grep -i "nyse euronext" book_3972.objects  
53729 Org 88974 # NYSE Euronext
53732 Org 88978 # NYSE Euronext
53745 Org 88997 # NYSE Euronext
53747 LocOrg 88999 # NYSE Euronext
53750 Org 89002 # NYSE Euronext
53751 Org 89003 # NYSE Euronext
53763 Org 89027 # NYSE Euronext
53790 Org 89055 89056 # компания ICE — NYSE Euronext

$ grep -i "deutsche börse" book_3972.objects 
53731 LocOrg 88976 88977 # франкфуртскую Deutsche Börse
53733 Org 88979 # Deutsche Börse
53783 Org 89042 89043 # Deutsche Börse франкфуртской

Т.е. тип Org вроде есть.

**Comment by AndreyAv** [comment]
Странно. 
Это вторая дорожка БЕЗ аргумента -m

**Comment by vbocharov** [comment]
@StanDzh почему мы требуем, чтобы это были именно локации?

**Comment by StanDzh** [comment]
А можно попросить весь .report?

**Comment by AndreyAv** [comment]
------STANDARD------
   1.00 PER [lastname : нидерауэр, firstname : данкан]   =   PER [lastname : нидерауэр, firstname : данкан]
   1.00 PER [lastname : спрекер, firstname : джефф] =   PER [lastname : спрекер, firstname : джефф]
   1.00 LOC [name : америка | сша]    =   LOC [name : америка]
   1.00 LOC [name : нью-йорк]    =   LOC [name : нью-йорк]
   1.00 LOC [name : атланта] =   LOC [name : атланта]
   1.00 LOC [name : уолл-стрит]    =   LOC [name : уолл-стрит]
   1.00 ORG [name : hong kong exchanges & clearing | exchanges & clearing]  =   ORG [name : hong kong exchanges & clearing]
   1.00 ORG [name : cme group]  =   ORG [name : cme group]
   1.00 ORG [name : nasdaq] =   ORG [name : nasdaq]
   1.00 ORG [name : минюст | минюст сша] =   ORG [name : минюст сша]

   0.00 LOC [name : ice американская финансовая компания | американская финансовая компания ice | ice компания | ice | ice финансовая компания | финансовая компания ice | компания ice]
   0.00 LOC [name : нью-йоркская фондовая биржа главная биржа мира | nyse euronext главная биржа мира | nyse фондовая биржа | биржа nyse | биржа nyse euronext | главная биржа мира нью-йоркская фондовая биржа | nyse биржа | главная биржа nyse euronext | фондовая биржа nyse euronext | главная биржа мира nyse | nyse euronext биржа | nyse главная биржа | нью-йоркская фондовая биржа | nyse | nyse главная биржа мира | нью-йоркская фондовая биржа главная биржа | главная биржа нью-йоркская фондовая биржа | nyse euronext | главная биржа nyse | главная биржа мира nyse euronext | фондовая биржа nyse | nyse euronext фондовая биржа | nyse euronext главная биржа]
   0.00 LOC [name : deutsche börse | франкфуртская deutsche börse]
IGNORED LOC [name : франкфурт]
IGNORED LOC [name : европа]
   0.00 ORG [name : объединенная компания ice — nyse euronext | ice — nyse euronext компания | ice — nyse euronext биржа | биржа ice — nyse euronext | ice — nyse euronext объединенная компания | ice — nyse euronext | компания ice — nyse euronext | объединенная биржа ice — nyse euronext | ice — nyse euronext объединенная биржа]

--------TEST--------
   1.00 PER [lastname : нидерауэр, firstname : данкан]   =   PER [lastname : нидерауэр, firstname : данкан]
   1.00 PER [lastname : спрекер, firstname : джефф] =   PER [lastname : спрекер, firstname : джефф]
   1.00 LOC [name : америка] =   LOC [name : америка | сша]
   1.00 LOC [name : нью-йорк]    =   LOC [name : нью-йорк]
   1.00 LOC [name : атланта] =   LOC [name : атланта]
   1.00 LOC [name : уолл-стрит]    =   LOC [name : уолл-стрит]
   1.00 ORG [name : hong kong exchanges & clearing] =   ORG [name : hong kong exchanges & clearing | exchanges & clearing]
   1.00 ORG [name : cme group]  =   ORG [name : cme group]
   1.00 ORG [name : nasdaq] =   ORG [name : nasdaq]
   1.00 ORG [name : минюст сша]    =   ORG [name : минюст | минюст сша]

   0.00 ORG [name : офис ice]
   0.00 ORG [name : nyse euronext]
   0.00 ORG [name : франкфуртская deutsche börse]

**Comment by vbocharov** [comment]
@AndreyAv судя по нынешней разметке эталона, это должно было исправиться. Проверьте, пожалуйста.
