### ISSUE TITLE
book_3966. Объединение сущностей

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#58]
Вторая дорожка:
Оштрафовали за то, что мы не выделили:

> 0.00 ORG [name : онф]

При этом есть сущность 

> 1.00 ORG [name : общероссийский народный фронт]        =             ORG [name : общероссийский народный фронт]

С которой в нашем случае и произошло объединение ОНФ. Считаю, что это правильно.

**Comment by vbocharov** [comment]
Исправил в эталоне.
