### ISSUE TITLE
book_3962. Проблема с пробелами

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#61]
Получили штраф из-за того, что выделили сущность

> 0.00 ORG [name : камерный музыкальный театр им. б.а. покровского]

А компаратор ожидал такую:

> 0.00 ORG [name : камерный музыкальный театр им . б . а . покровского]

Здесь как минимум нужно засчитывать оба варианта.

**Comment by vbocharov** [comment]
Добавил ещё один вариант с приклеенными точками к словам справа

**Comment by vbocharov** [comment]
Переоткройте, если не поможет.

**Comment by AndreyAv** [comment]
Да, конечно
