### ISSUE TITLE
Дорожка 3, 3688

### ISSUE THREAD

**Issue by mariarusia** [dialogue-evaluation/factRuEval-2016#62]
3688-0 Occupation
Who obj3564 Путин Владимир 
Job span87327 президент
Where obj3567 Россия
Сложность повышенная

3688-4 Occupation
Who obj3574 Песков Дмитрий 
Job span87351 Пресс-секретарь
Where obj3567 Россия
Сложность повышенная

В тексте нигде нет про то, что Путин работает в России, про Пескова тоже.

**Comment by Shnurre** [comment]
"Во вторник президент Владимир Путин должен обсудить регулирование Рунета с крупнейшими интернет-компаниями.

Как сообщал РБК, в рамках форума "Интернет-предпринимательство в России", который пройдет в Москве 10 июня, Путин может провести встречу с первыми лицами российских интернет-компаний."

Я считаю, что по такому фрагменту однозначно( или с высокой вероятностьюя ) понимается, что Путин - президент именно России(с повышенной сложностью, разумеется).

Песков - пресс-секретарь Путина, у Путина наниматель - Россия. В этом случае нанимателем Пескова тоже считается Россия, похожий случай был в интсрукции

**Comment by mariarusia** [comment]
Я так понимаю, имеется в виду пункт 9

"В случае, если в факте работы персона является представителем организации X при организации Y, то в поле «Где» следует помещать название организации X. Например, для факта «посол Италии в Грузии» нанимателем является Италия, а не Грузия. Если организация X не может быть определена точно, то в поле «Где» должна попадать организация более высокого порядка, упомянутая в тексте. Например, у факта «полпред президента РФ в Северо-Кавказском федеральном округе» реальным нанимателем является организация «администрация президента РФ», но поскольку она в тексте не упомянута, в поле «Где» следует поместить LocOrg «РФ»."

Но это про организацию при организации. С персонами принципиально не так. В противном случае "личный врач директора Гугла" должен работать в Гугл. Или какой-то другой пункт инструкции?

"Необходимо извлекать только те факты, о которых тем или иным образом явно написано в тексте."
Здесь имхо никак явно не прописано, что Путин работает в России. Медведев регулярно встречался в Силиконовой  долине с представителями американской интернет-индустрии, будучи президентом РФ.

**Comment by Shnurre** [comment]
См. тикет 63.

**Comment by vbocharov** [comment]
https://github.com/dialogue-evaluation/factRuEval-2016/issues/63
