### ISSUE TITLE
3700. Дорожка 3

### ISSUE THREAD

**Issue by mariarusia** [dialogue-evaluation/factRuEval-2016#63]
3700

у Путина указана должность и Россия в месте работы, также нигде в тексте нет.

Он там говорит о присоединении Крыма, но напрямую из текста не выводится

**Comment by Shnurre** [comment]
Аналогично тикету 62. 
Фрагмент, на котором понимается наниматель:
а днях телеканал «Россия 1» показал анонс фильма «Путь на Родину». В этом фрагменте Владимир Путин говорит о том, как началась работа «по возврату Крыма в состав России». Президент рассказал, как «пригласил в Кремль руководителей наших специальных служб, Министерства обороны» и поставил перед ними задачу спасти жизнь SPAN87159(президента) Украины Виктора Януковича, иначе «его просто уничтожили бы». «Это было между 22-м и 23-м февраля, мы закончили около 7 часов утра. И, расставаясь, я всем коллегам сказал: мы вынуждены начать работу по возврату Крыма в состав России», – цитирует РБК Путина.

**Comment by mariarusia** [comment]
Да тоже явно не сказано в тексте.

Повышенная сложность, имхо, это про кореференцию.

"Президенты России и Франции встретились - Путин и Саркози обсудили"

То, что Путин возвращает Крым в Россию, не говорит, что он президент России. Нуланд регулярно хочет вернуть Крым в Украину, при этом она из США. Имхо, это случай на экстралингвистические знания

**Comment by Shnurre** [comment]
Я считаю, что эта ситуация абсолютно аналогична корефереции. Строго говоря, если написано "Бьорндален - известный норвежский биатлонист. Спортсмен дал нам интервью", мы тоже не можем однозначно сделать вывод, что интервью дал Бьорндален. Однако, такой вывод делается всегда.

**Comment by vbocharov** [comment]
Думаю, что это было бы логично, если бы мы системно размечали кореференцию между ФИО и должность+компания. Сейчас давайте уберём эти факты.
