### ISSUE TITLE
book_3962. Россия-Франция

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#64]
> доктор искусствоведения Екатерина Купровская-Денисова (Россия-Франция)

В нашем раборе (дорожки 1 и 2) выделяется 

> 0.00 LOC [name : россия-франция]

В разметке Россия и Франция выделены в две отдельные локации. Вопрос спорный, но мне кажется, что за выделение одной локации Россия-Франция вместо двух в данном контексте штрафовать не надо.

**Comment by vbocharov** [comment]
Насколько я понимаю, сделать опциональное неразличение объектов компаратор не сможет. @StanDzh: это верно?

**Comment by StanDzh** [comment]
Да, такое, боюсь, поддержать не получится.

**Comment by vbocharov** [comment]
Закрываю, по двум причинам:
1) не можем сделать альтернативный вариант
2) это редкий случай, к которому модель разметки оказалась не готова
