### ISSUE TITLE
3962. Неправильно устанавливается связь

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#69]
В разметке неправильно устанавливается следующая связь:

> PER [patronymic : а, lastname : покровский, firstname : б]       =             PER [lastname : фон, lastname : вебера, firstname : к, patronymic : м]

**Comment by StanDzh** [comment]
По-моему, проблема в нечетком сравнении строк, сейчас поправлю. Не могли бы Вы привести фрагмент тестовой разметки с Вебером и Покровским (если он там есть)?

**Comment by AndreyAv** [comment]
> IGNORED   PER [lastname : фон, lastname : вебера, firstname : к, patronymic : м]   =   PER [patronymic : а, lastname : покровский, firstname : б]
