### ISSUE TITLE
Сроки

### ISSUE THREAD

**Issue by al07** [dialogue-evaluation/factRuEval-2016#7]
Здравствуйте, а какие теперь сроки конкурса? По старому плану 17 числа надо было присылать результаты? Какие теперь сроки?

**Comment by vbocharov** [comment]
17 будет бессмысленно, т.к. тестовая коллекция пока не размечена.
Мы над нею работаем. Присоединяйтесь ;)

**Comment by FedorBykov** [comment]
Уважаемые организаторы, может быть сориентируете хотя бы приблизительно по срокам (хотя бы относительным)
1. Появления компаратора для второй и третьей дорожек
2. Появления тестовой коллекции 
3. Времени на обработку тестовой коллекции - все-таки это будет неделя или два дня (как фигурировало в http://habrahabr.ru/company/abbyy/blog/273965/) 
4. Объему тестовой коллекции (одно дело 10000 документов, другое дело 100000)
Заранее спасибо!

**Comment by vbocharov** [comment]
1. ~ 26 января
2. ~ 2 февраля
3. 5 дней
4. напишу, когда сгенерирую её. Где-то между этими двумя цифрами.

**Comment by FedorBykov** [comment]
Спасибо!

**Comment by konstantin-smith** [comment]
К организаторам у меня организационная просьба: информировать о выкладывании измененных коллекций. А то позавчера случайно обнаружил, что появилось множество coref, то есть теперь можно работать со 2-й дорожкой. А если бы не посмотрел, то не узнал. Предлагаю создать раздел и помещать туда записи об изменениях.  Обидно, если появится основная (тестовая) коллекция, а кто-то (я) узнает об этом поздно.  Спасибо!

**Comment by vbocharov** [comment]
Обо всех оргвопросах мы пишем в почту. Если вы читаете почту, то ничего важного не пропустите.

**Comment by konstantin-smith** [comment]
Уважаемые организаторы! Исходя из текущей ситуации, есть какой-нибудь прогноз по срокам?

**Comment by sysoev-a** [comment]
Уважаемые организаторы! Не могли бы вы озвучить новые сроки. Спасибо.

**Comment by vbocharov** [comment]
Пишу письмо об этом. Днём, судя по всему, оно придёт всем.

**Comment by FedorBykov** [comment]
Никаких писем по поводу сроков вчера не получал. Я что-то пропустил?

**Comment by sysoev-a** [comment]
Уважаемые организаторы! Есть ли какая-нибудь информация по срокам?

**Comment by konstantin-smith** [comment]
1) Традиционный вопрос по срокам
2) Скажите, а не могли бы Вы выложить ещё сотню-другую текстов (в другую папку)? Дело в том, что на текущих 122 не всё понятно с некоторыми ситуациями. Например, для азиатских имён в разных местах по-разному. Скажем, "Ким Ир Сен" в одних случаях firstname:Ир (Сен пропадает), в других firstname: Ир Сен.  Для "Аун Сан Су Чжи" размечающий не знал, что тут что (да и я не знаю), поэтому просто оставил один lastname: Аун Сан.  Интернет в одних случаях считается организацией, в других игнорируется. И т.д. Более половины из этих 122 текстов содержат ошибки и спорные моменты. Исправлять их бесполезно, но можно учесть, чтобы максимизировать результирующую Ф-меру.  В связи с этим и просьба о предоставлении дополнительного набора текстов - на фоне основного набора "лишняя" сотня-другая документов роли не играет.  Набор этот предоставляется "as is" без приёма претензий по качеству.
Спасибо!

**Comment by vbocharov** [comment]
Вот тут актуальные сроки:
https://github.com/dialogue-evaluation/factRuEval-2016/blob/master/README.md
