### ISSUE TITLE
3962. Названия опер

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#70]
В разметке 

>    0.00 PER [firstname : идоменей]
>    0.00 PER [firstname : пинто]

На самом деле, это названия опер: «Идоменей» и «Три Пинто». Может эти сущности вообще не учитывать?

**Comment by vbocharov** [comment]
Там очень много таких примеров. Даже в том же тексте.

@StanDzh что сделает компаратор, если я сейчас добавлю новый тип спана, обозначающий название худ. произведения, поставлю его на "Идоменей" и создам объект во втором слое тоже с новым типом?

**Comment by StanDzh** [comment]
Ну, есть шанс, что все сломается, т.к. в компараторе есть минимальная валидация типов (чтобы защититься от опечаток и ошибок в эталоне) но если ты мне скажешь названия, то я сделаю обработку как для Project. Мы хотим игнорировать эти сущности 'жестко', т.е. вообще исключать из сравнения, правильно?

**Comment by vbocharov** [comment]
В целом, я согласен с тем, что такие случаи нужно было размечать иначе. Переделывать сейчас не буду, чтобы не сломался компаратор. Скорее всего почти у всех участников будут одинаковые ошибки в этом месте.
