### ISSUE TITLE
3954. Карамба

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#72]
Выделяется сущность

> ORG [name : caramba tv]

Но, при этом, мы получаем штраф за отсутствие сущности

> 0.00 ORG [name : сайт caramba tv | ресурс сайт caramba tv | сайт caramba tv ресурс]

Правильно ли это? Ведь сайт - это не организация

**Comment by vbocharov** [comment]
Поставил тег Facility. Теперь не должен учитываться как организация.
