### ISSUE TITLE
Евросоюз. Тип сущности

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#75]
В issue Список вопросов по логике NER #12 @FedorBykov задавал вопрос про тип сущности Евросоюз. Решили, что это именно ORG. В файлах **3940, 3744, 3820, 3746, 3910** TestSet'а Евросоюз (ЕС) - LOC. Исправьте, пожалуйста.

**Comment by vbocharov** [comment]
Думаю, что уже исправил это вчера вечером. Возьмите свежую версию, проверьте и, если где-то ещё осталось, то переоткройте, пожалуйста.
