### ISSUE TITLE
3940. Россия

### ISSUE THREAD

**Issue by AndreyAv** [dialogue-evaluation/factRuEval-2016#77]
Вторая дорожка. Получили штраф за невыделение сущности

>  0.00 LOC [name : россия государство | государство россия | россия]

В тексте я нашел только "российского лидера", "российским руководством"

**Comment by vbocharov** [comment]
attn @StanDzh 

там три упоминания:
- одно создано из дескриптора "государство"
- два других - из прилагательных geo_adj

ИМХО, не надо штрафовать в этом случае.

**Comment by StanDzh** [comment]
Поправил в последнем коммите
