### ISSUE TITLE
Корректность результата

### ISSUE THREAD

**Issue by konstantin-smith** [dialogue-evaluation/factRuEval-2016#8]
Интересно, а как отличить машинный прогон от ручной корректировки? Правильно - никак!  Если тексты для прогона даются на неделю, а вручную текст можно разметить в среднем за 2 мин (файлы task1 & task2), то один чел. за неделю "прогонит" через себя 1500 текстов. А если посадить несколько человек?

Для чистоты эксперимента было бы корректнее потребовать со стороны участников:
1) либо реализацию исполняемых модулей, запускаемых на проверяющей стороне; 
2) либо реализацию web-сервиса с функцией обработки текста, если невозможно предоставление таких модулей;
3) либо сильно ограничить срок формирования результата (например, несколькими часами).

Что думаете?

**Comment by vbocharov** [comment]
Мы планируем сделать сделать так:

тестовая коллекция, которая будет выдана участникам, будет включать в себя несколько десятков тысяч документов (не более 100 тысяч). Осмысленная ручная обработка такого количества документов за неделю кажется нецелесообразной. Документы, входящие в оценочную выборку будут составлять около 1% от объёма коллекции. Отличить их будет трудно, т.к. документы будут взяты из одних и тех же источников.
